org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.249
loader_version_range=[1,)

mod_id=ascendant_equipment
mod_name=Ascendant Equipment
mod_license=MIT
mod_version=0.0.0-beta.2
mod_framework=neoforge
mod_group_id=com.skd.ascendantequipment

mixin=true
mixin_version=0.8.7
